service: auction-service

plugins:
#   - serverless-bundle
  - serverless-pseudo-parameters

package:
  individually: true
  exclude:
    - node_modules/**
    - package-lock.json
    - package.json

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}


layers:
  AuctionUuid:
    name: AuctionUuid
    path: layers/auction-uuid
    description: uuid layer to generate unique id
    compatibleRuntimes: [nodejs14.x,nodejs12.x]
    retain: false

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}

  
functions:
  hello:
    handler: hello.handler
    events:
      - http:
          method: GET
          path: /hello

  createAuction:
    handler: createAuction.handler
    layers:
      - {Ref : AuctionUuidLambdaLayer}
    events:
      - http:
          method: POST
          path: /auction




custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn:  !GetAtt AuctionsTable.Arn